### PR TITLE
Add option to include a signature, conditionally.

### PR DESCRIPTION
**Pull request by the-solipsist**
I've added an option to conditionally include a signature.  I've changed the template, the yaml file, as well as the readme to provide instructions on how to use it.

### CODE REVIEW

**Comment by mrzool** [comment]
Not sure about this one… who puts a signature on an invoice? I never had to send out a signed invoice nor ever received one. Couldn't find a country where signing invoices is required by law. Seems unnecessary to be honest.

**Comment by the-solipsist** [comment]
In India, it is mandatory to have [signed invoices](https://www.cbic.gov.in/resources//htdocs-cbec/gst/tax-invoice-efliers.pdf;jsessionid=3D168CAF97C7D7768E9DA3F9B30B889F) (either through a pen-and-paper signature or through a digital (cryptographic) signature) for tax purposes, and there's [software to help you do that](https://www.billingsoftware.in/add-signature-in-invoice.html) as well.

**Comment by the-solipsist** [comment]
And further, if there's a `closingnote`, then it makes sense to allow for an optional signature even in contexts where a signature isn't legally mandated.

**Comment by mrzool** [comment]
My bad, looks like I didn't search hard enough. I'll have another look at this asap, reopening in the meantime.

**Comment by mrzool** [comment]
Ended up implementing this myself in 7569fde, without adding any additional option, consistent with how the same feature is implemented in [letter-boilerplate](https://github.com/mrzool/letter-boilerplate).

Thanks for the input!

**Pull request closed without merging**
